name: Update and Clean GTFS

permissions:
  contents: write

on:
  schedule:
    - cron: "0 /6 * * *"
  workflow_dispatch:

jobs:
  download_and_clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: pip install requests python-dotenv

      - name: Download latest GTFS feeds
        env:
          NAP_API_KEY: ${{ secrets.NAP_API_KEY }}
        run: python download_gtfs.py

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Clone and build gtfstidy
        run: |
          git clone https://github.com/patrickbr/gtfstidy.git
          cd gtfstidy
          make build

      - name: Add gtfstidy to PATH
        run: echo "${{ github.workspace }}/gtfstidy" >> $GITHUB_PATH

      - name: Run gtfstidy to clean and merge feeds
        run: |
          export PATH=$PATH:$HOME/go/bin
          for g in es_*.zip; do
            gtfstidy "$g" --fix --fix-zip --remove-red-services --keep-ids --remove-fillers --drop-shapes --delete-orphans --output "$g"
          done > tidy.log
          gtfstidy -E --drop-shapes --keep-ids -AC es_*.zip -o gtfs_valencia_clean.zip --fix --remove-fillers >> tidy.log

      - name: Commit and push cleaned feed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add gtfs_valencia_clean.zip tidy.log es_mapping.json 
          git commit -m "Update and clean merged GTFS feed" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

